// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.grpc.infrastructure;

public interface CategoryListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.grpc.CategoryList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  java.util.List<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo> 
      getCategoryInfoList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  io.reactivesw.catelog.grpc.infrastructure.CategoryInfo getCategoryInfo(int index);
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  int getCategoryInfoCount();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  java.util.List<? extends io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder> 
      getCategoryInfoOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder getCategoryInfoOrBuilder(
      int index);
}
