// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.grpc.infrastructure;

public interface CategoryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.grpc.CategoryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional int32 displayOrder = 4;</code>
   */
  int getDisplayOrder();

  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo subCategoryInfos = 5;</code>
   */
  java.util.List<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo> 
      getSubCategoryInfosList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo subCategoryInfos = 5;</code>
   */
  io.reactivesw.catelog.grpc.infrastructure.CategoryInfo getSubCategoryInfos(int index);
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo subCategoryInfos = 5;</code>
   */
  int getSubCategoryInfosCount();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo subCategoryInfos = 5;</code>
   */
  java.util.List<? extends io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder> 
      getSubCategoryInfosOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo subCategoryInfos = 5;</code>
   */
  io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder getSubCategoryInfosOrBuilder(
      int index);
}
