// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.grpc.infrastructure;

/**
 * <pre>
 **
 * response when call queryAllCategories.
 * </pre>
 *
 * Protobuf type {@code io.reactivesw.catelog.grpc.CategoryList}
 */
public  final class CategoryList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catelog.grpc.CategoryList)
    CategoryListOrBuilder {
  // Use CategoryList.newBuilder() to construct.
  private CategoryList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CategoryList() {
    categoryInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CategoryList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              categoryInfo_ = new java.util.ArrayList<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            categoryInfo_.add(input.readMessage(io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        categoryInfo_ = java.util.Collections.unmodifiableList(categoryInfo_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_CategoryList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_CategoryList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catelog.grpc.infrastructure.CategoryList.class, io.reactivesw.catelog.grpc.infrastructure.CategoryList.Builder.class);
  }

  public static final int CATEGORYINFO_FIELD_NUMBER = 1;
  private java.util.List<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo> categoryInfo_;
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  public java.util.List<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo> getCategoryInfoList() {
    return categoryInfo_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  public java.util.List<? extends io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder> 
      getCategoryInfoOrBuilderList() {
    return categoryInfo_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  public int getCategoryInfoCount() {
    return categoryInfo_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  public io.reactivesw.catelog.grpc.infrastructure.CategoryInfo getCategoryInfo(int index) {
    return categoryInfo_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
   */
  public io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder getCategoryInfoOrBuilder(
      int index) {
    return categoryInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < categoryInfo_.size(); i++) {
      output.writeMessage(1, categoryInfo_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < categoryInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, categoryInfo_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catelog.grpc.infrastructure.CategoryList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * response when call queryAllCategories.
   * </pre>
   *
   * Protobuf type {@code io.reactivesw.catelog.grpc.CategoryList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catelog.grpc.CategoryList)
      io.reactivesw.catelog.grpc.infrastructure.CategoryListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_CategoryList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_CategoryList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catelog.grpc.infrastructure.CategoryList.class, io.reactivesw.catelog.grpc.infrastructure.CategoryList.Builder.class);
    }

    // Construct using io.reactivesw.catelog.grpc.infrastructure.CategoryList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getCategoryInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (categoryInfoBuilder_ == null) {
        categoryInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        categoryInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_CategoryList_descriptor;
    }

    public io.reactivesw.catelog.grpc.infrastructure.CategoryList getDefaultInstanceForType() {
      return io.reactivesw.catelog.grpc.infrastructure.CategoryList.getDefaultInstance();
    }

    public io.reactivesw.catelog.grpc.infrastructure.CategoryList build() {
      io.reactivesw.catelog.grpc.infrastructure.CategoryList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catelog.grpc.infrastructure.CategoryList buildPartial() {
      io.reactivesw.catelog.grpc.infrastructure.CategoryList result = new io.reactivesw.catelog.grpc.infrastructure.CategoryList(this);
      int from_bitField0_ = bitField0_;
      if (categoryInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          categoryInfo_ = java.util.Collections.unmodifiableList(categoryInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.categoryInfo_ = categoryInfo_;
      } else {
        result.categoryInfo_ = categoryInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catelog.grpc.infrastructure.CategoryList) {
        return mergeFrom((io.reactivesw.catelog.grpc.infrastructure.CategoryList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catelog.grpc.infrastructure.CategoryList other) {
      if (other == io.reactivesw.catelog.grpc.infrastructure.CategoryList.getDefaultInstance()) return this;
      if (categoryInfoBuilder_ == null) {
        if (!other.categoryInfo_.isEmpty()) {
          if (categoryInfo_.isEmpty()) {
            categoryInfo_ = other.categoryInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCategoryInfoIsMutable();
            categoryInfo_.addAll(other.categoryInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.categoryInfo_.isEmpty()) {
          if (categoryInfoBuilder_.isEmpty()) {
            categoryInfoBuilder_.dispose();
            categoryInfoBuilder_ = null;
            categoryInfo_ = other.categoryInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            categoryInfoBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCategoryInfoFieldBuilder() : null;
          } else {
            categoryInfoBuilder_.addAllMessages(other.categoryInfo_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catelog.grpc.infrastructure.CategoryList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catelog.grpc.infrastructure.CategoryList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo> categoryInfo_ =
      java.util.Collections.emptyList();
    private void ensureCategoryInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        categoryInfo_ = new java.util.ArrayList<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo>(categoryInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.grpc.infrastructure.CategoryInfo, io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder, io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder> categoryInfoBuilder_;

    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public java.util.List<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo> getCategoryInfoList() {
      if (categoryInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(categoryInfo_);
      } else {
        return categoryInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public int getCategoryInfoCount() {
      if (categoryInfoBuilder_ == null) {
        return categoryInfo_.size();
      } else {
        return categoryInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.CategoryInfo getCategoryInfo(int index) {
      if (categoryInfoBuilder_ == null) {
        return categoryInfo_.get(index);
      } else {
        return categoryInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder setCategoryInfo(
        int index, io.reactivesw.catelog.grpc.infrastructure.CategoryInfo value) {
      if (categoryInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoryInfoIsMutable();
        categoryInfo_.set(index, value);
        onChanged();
      } else {
        categoryInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder setCategoryInfo(
        int index, io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder builderForValue) {
      if (categoryInfoBuilder_ == null) {
        ensureCategoryInfoIsMutable();
        categoryInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        categoryInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder addCategoryInfo(io.reactivesw.catelog.grpc.infrastructure.CategoryInfo value) {
      if (categoryInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoryInfoIsMutable();
        categoryInfo_.add(value);
        onChanged();
      } else {
        categoryInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder addCategoryInfo(
        int index, io.reactivesw.catelog.grpc.infrastructure.CategoryInfo value) {
      if (categoryInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoryInfoIsMutable();
        categoryInfo_.add(index, value);
        onChanged();
      } else {
        categoryInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder addCategoryInfo(
        io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder builderForValue) {
      if (categoryInfoBuilder_ == null) {
        ensureCategoryInfoIsMutable();
        categoryInfo_.add(builderForValue.build());
        onChanged();
      } else {
        categoryInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder addCategoryInfo(
        int index, io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder builderForValue) {
      if (categoryInfoBuilder_ == null) {
        ensureCategoryInfoIsMutable();
        categoryInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        categoryInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder addAllCategoryInfo(
        java.lang.Iterable<? extends io.reactivesw.catelog.grpc.infrastructure.CategoryInfo> values) {
      if (categoryInfoBuilder_ == null) {
        ensureCategoryInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, categoryInfo_);
        onChanged();
      } else {
        categoryInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder clearCategoryInfo() {
      if (categoryInfoBuilder_ == null) {
        categoryInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        categoryInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public Builder removeCategoryInfo(int index) {
      if (categoryInfoBuilder_ == null) {
        ensureCategoryInfoIsMutable();
        categoryInfo_.remove(index);
        onChanged();
      } else {
        categoryInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder getCategoryInfoBuilder(
        int index) {
      return getCategoryInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder getCategoryInfoOrBuilder(
        int index) {
      if (categoryInfoBuilder_ == null) {
        return categoryInfo_.get(index);  } else {
        return categoryInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public java.util.List<? extends io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder> 
         getCategoryInfoOrBuilderList() {
      if (categoryInfoBuilder_ != null) {
        return categoryInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(categoryInfo_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder addCategoryInfoBuilder() {
      return getCategoryInfoFieldBuilder().addBuilder(
          io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder addCategoryInfoBuilder(
        int index) {
      return getCategoryInfoFieldBuilder().addBuilder(
          index, io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.CategoryInfo categoryInfo = 1;</code>
     */
    public java.util.List<io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder> 
         getCategoryInfoBuilderList() {
      return getCategoryInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.grpc.infrastructure.CategoryInfo, io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder, io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder> 
        getCategoryInfoFieldBuilder() {
      if (categoryInfoBuilder_ == null) {
        categoryInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.reactivesw.catelog.grpc.infrastructure.CategoryInfo, io.reactivesw.catelog.grpc.infrastructure.CategoryInfo.Builder, io.reactivesw.catelog.grpc.infrastructure.CategoryInfoOrBuilder>(
                categoryInfo_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        categoryInfo_ = null;
      }
      return categoryInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catelog.grpc.CategoryList)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catelog.grpc.CategoryList)
  private static final io.reactivesw.catelog.grpc.infrastructure.CategoryList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catelog.grpc.infrastructure.CategoryList();
  }

  public static io.reactivesw.catelog.grpc.infrastructure.CategoryList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CategoryList>
      PARSER = new com.google.protobuf.AbstractParser<CategoryList>() {
    public CategoryList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CategoryList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CategoryList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CategoryList> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catelog.grpc.infrastructure.CategoryList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

