// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.grpc.infrastructure;

/**
 * <pre>
 **
 *  response when call queryAllProductsByCategory.
 * </pre>
 *
 * Protobuf type {@code io.reactivesw.catelog.grpc.ProductBriefList}
 */
public  final class ProductBriefList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catelog.grpc.ProductBriefList)
    ProductBriefListOrBuilder {
  // Use ProductBriefList.newBuilder() to construct.
  private ProductBriefList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProductBriefList() {
    productBriefInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProductBriefList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              productBriefInfo_ = new java.util.ArrayList<io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            productBriefInfo_.add(input.readMessage(io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        productBriefInfo_ = java.util.Collections.unmodifiableList(productBriefInfo_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_ProductBriefList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_ProductBriefList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catelog.grpc.infrastructure.ProductBriefList.class, io.reactivesw.catelog.grpc.infrastructure.ProductBriefList.Builder.class);
  }

  public static final int PRODUCTBRIEFINFO_FIELD_NUMBER = 3;
  private java.util.List<io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo> productBriefInfo_;
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  public java.util.List<io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo> getProductBriefInfoList() {
    return productBriefInfo_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  public java.util.List<? extends io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfoOrBuilder> 
      getProductBriefInfoOrBuilderList() {
    return productBriefInfo_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  public int getProductBriefInfoCount() {
    return productBriefInfo_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  public io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo getProductBriefInfo(int index) {
    return productBriefInfo_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  public io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfoOrBuilder getProductBriefInfoOrBuilder(
      int index) {
    return productBriefInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < productBriefInfo_.size(); i++) {
      output.writeMessage(3, productBriefInfo_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < productBriefInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, productBriefInfo_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catelog.grpc.infrastructure.ProductBriefList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   *  response when call queryAllProductsByCategory.
   * </pre>
   *
   * Protobuf type {@code io.reactivesw.catelog.grpc.ProductBriefList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catelog.grpc.ProductBriefList)
      io.reactivesw.catelog.grpc.infrastructure.ProductBriefListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_ProductBriefList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_ProductBriefList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catelog.grpc.infrastructure.ProductBriefList.class, io.reactivesw.catelog.grpc.infrastructure.ProductBriefList.Builder.class);
    }

    // Construct using io.reactivesw.catelog.grpc.infrastructure.ProductBriefList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getProductBriefInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (productBriefInfoBuilder_ == null) {
        productBriefInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        productBriefInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catelog.grpc.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_ProductBriefList_descriptor;
    }

    public io.reactivesw.catelog.grpc.infrastructure.ProductBriefList getDefaultInstanceForType() {
      return io.reactivesw.catelog.grpc.infrastructure.ProductBriefList.getDefaultInstance();
    }

    public io.reactivesw.catelog.grpc.infrastructure.ProductBriefList build() {
      io.reactivesw.catelog.grpc.infrastructure.ProductBriefList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catelog.grpc.infrastructure.ProductBriefList buildPartial() {
      io.reactivesw.catelog.grpc.infrastructure.ProductBriefList result = new io.reactivesw.catelog.grpc.infrastructure.ProductBriefList(this);
      int from_bitField0_ = bitField0_;
      if (productBriefInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          productBriefInfo_ = java.util.Collections.unmodifiableList(productBriefInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.productBriefInfo_ = productBriefInfo_;
      } else {
        result.productBriefInfo_ = productBriefInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catelog.grpc.infrastructure.ProductBriefList) {
        return mergeFrom((io.reactivesw.catelog.grpc.infrastructure.ProductBriefList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catelog.grpc.infrastructure.ProductBriefList other) {
      if (other == io.reactivesw.catelog.grpc.infrastructure.ProductBriefList.getDefaultInstance()) return this;
      if (productBriefInfoBuilder_ == null) {
        if (!other.productBriefInfo_.isEmpty()) {
          if (productBriefInfo_.isEmpty()) {
            productBriefInfo_ = other.productBriefInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProductBriefInfoIsMutable();
            productBriefInfo_.addAll(other.productBriefInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.productBriefInfo_.isEmpty()) {
          if (productBriefInfoBuilder_.isEmpty()) {
            productBriefInfoBuilder_.dispose();
            productBriefInfoBuilder_ = null;
            productBriefInfo_ = other.productBriefInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            productBriefInfoBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getProductBriefInfoFieldBuilder() : null;
          } else {
            productBriefInfoBuilder_.addAllMessages(other.productBriefInfo_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catelog.grpc.infrastructure.ProductBriefList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catelog.grpc.infrastructure.ProductBriefList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo> productBriefInfo_ =
      java.util.Collections.emptyList();
    private void ensureProductBriefInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        productBriefInfo_ = new java.util.ArrayList<io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo>(productBriefInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfoOrBuilder> productBriefInfoBuilder_;

    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public java.util.List<io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo> getProductBriefInfoList() {
      if (productBriefInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(productBriefInfo_);
      } else {
        return productBriefInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public int getProductBriefInfoCount() {
      if (productBriefInfoBuilder_ == null) {
        return productBriefInfo_.size();
      } else {
        return productBriefInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo getProductBriefInfo(int index) {
      if (productBriefInfoBuilder_ == null) {
        return productBriefInfo_.get(index);
      } else {
        return productBriefInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder setProductBriefInfo(
        int index, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo value) {
      if (productBriefInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductBriefInfoIsMutable();
        productBriefInfo_.set(index, value);
        onChanged();
      } else {
        productBriefInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder setProductBriefInfo(
        int index, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder builderForValue) {
      if (productBriefInfoBuilder_ == null) {
        ensureProductBriefInfoIsMutable();
        productBriefInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        productBriefInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder addProductBriefInfo(io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo value) {
      if (productBriefInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductBriefInfoIsMutable();
        productBriefInfo_.add(value);
        onChanged();
      } else {
        productBriefInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder addProductBriefInfo(
        int index, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo value) {
      if (productBriefInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductBriefInfoIsMutable();
        productBriefInfo_.add(index, value);
        onChanged();
      } else {
        productBriefInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder addProductBriefInfo(
        io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder builderForValue) {
      if (productBriefInfoBuilder_ == null) {
        ensureProductBriefInfoIsMutable();
        productBriefInfo_.add(builderForValue.build());
        onChanged();
      } else {
        productBriefInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder addProductBriefInfo(
        int index, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder builderForValue) {
      if (productBriefInfoBuilder_ == null) {
        ensureProductBriefInfoIsMutable();
        productBriefInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        productBriefInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder addAllProductBriefInfo(
        java.lang.Iterable<? extends io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo> values) {
      if (productBriefInfoBuilder_ == null) {
        ensureProductBriefInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productBriefInfo_);
        onChanged();
      } else {
        productBriefInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder clearProductBriefInfo() {
      if (productBriefInfoBuilder_ == null) {
        productBriefInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        productBriefInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public Builder removeProductBriefInfo(int index) {
      if (productBriefInfoBuilder_ == null) {
        ensureProductBriefInfoIsMutable();
        productBriefInfo_.remove(index);
        onChanged();
      } else {
        productBriefInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder getProductBriefInfoBuilder(
        int index) {
      return getProductBriefInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfoOrBuilder getProductBriefInfoOrBuilder(
        int index) {
      if (productBriefInfoBuilder_ == null) {
        return productBriefInfo_.get(index);  } else {
        return productBriefInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public java.util.List<? extends io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfoOrBuilder> 
         getProductBriefInfoOrBuilderList() {
      if (productBriefInfoBuilder_ != null) {
        return productBriefInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(productBriefInfo_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder addProductBriefInfoBuilder() {
      return getProductBriefInfoFieldBuilder().addBuilder(
          io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder addProductBriefInfoBuilder(
        int index) {
      return getProductBriefInfoFieldBuilder().addBuilder(
          index, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
     */
    public java.util.List<io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder> 
         getProductBriefInfoBuilderList() {
      return getProductBriefInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfoOrBuilder> 
        getProductBriefInfoFieldBuilder() {
      if (productBriefInfoBuilder_ == null) {
        productBriefInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfo.Builder, io.reactivesw.catelog.grpc.infrastructure.ProductBriefInfoOrBuilder>(
                productBriefInfo_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        productBriefInfo_ = null;
      }
      return productBriefInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catelog.grpc.ProductBriefList)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catelog.grpc.ProductBriefList)
  private static final io.reactivesw.catelog.grpc.infrastructure.ProductBriefList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catelog.grpc.infrastructure.ProductBriefList();
  }

  public static io.reactivesw.catelog.grpc.infrastructure.ProductBriefList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductBriefList>
      PARSER = new com.google.protobuf.AbstractParser<ProductBriefList>() {
    public ProductBriefList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductBriefList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductBriefList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductBriefList> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catelog.grpc.infrastructure.ProductBriefList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

