// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_product_message.proto

package io.reactivesw.catalog.grpc;

public interface GrpcAttributeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.GrpcAttribute)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string value = 3;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 3;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
