// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_data_message.proto

package io.reactivesw.catalog.grpc;

public interface StringValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.StringValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The string value.
   * </pre>
   *
   * <code>optional string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <pre>
   * The string value.
   * </pre>
   *
   * <code>optional string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
