package io.reactivesw.catalog.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * this is entity class for sku.
 * 
 * @author Davis
 *
 */
@Entity
@Table(name = "sw_sku")
public class Sku implements Serializable {
  /**
   * serialVersionUID.
   */
  private static final long serialVersionUID = 4440959875887801924L;

  /**
   * id for product. auto generated by database.
   */
  @Id
  @Column(name = "sku_id")
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  /**
   * skuNumber for sku.
   */
  @Size(max = 64)
  @Column(name = "sku_number", length = 64, nullable = false)
  private String skuNumber;

  /**
   * active for sku.
   */
  @Column(name = "is_active")
  private boolean active;

  /**
   * quantity for sku.
   */
  @Column(name = "quantity")
  private int quantity;

  /**
   * upc for sku.
   */
  @Size(max = 16)
  @Column(name = "upc", length = 16)
  private String upc;

  /**
   * display order for sku.
   */
  @Column(name = "display_order")
  private int displayOrder;

  /**
   * create time for sku.
   */
  @Column(name = "create_time")
  private Date createTime;

  /**
   * last modified time for sku.
   */
  @Column(name = "last_modified_time")
  private Date lastModifiedTime;

  /**
   * price for sku.
   */
  @Column(name = "price", precision = 19, scale = 5)
  private BigDecimal price;

  /**
   * medias for sku.
   */
  @OneToMany(cascade = CascadeType.REFRESH, fetch = FetchType.EAGER)
  @JoinTable(name = "sw_sku_media", joinColumns = @JoinColumn(name = "sku_id") ,
      inverseJoinColumns = @JoinColumn(name = "media_id") )
  private Set<Media> medias;

  /**
   * variant values for sku.
   */
  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
  @JoinTable(name = "sw_sku_variant_value", joinColumns = @JoinColumn(name = "sku_id") ,
      inverseJoinColumns = @JoinColumn(name = "variant_value_id") )
  private Set<VariantValue> variantValues;

  /**
   * product for sku.
   */
  @ManyToOne(targetEntity = Product.class, cascade = {CascadeType.MERGE, CascadeType.REFRESH},
      optional = false)
  @JoinColumn(name = "product_id")
  private Product product;

  /**
   * get id.
   * 
   * @return id
   */
  public long getId() {
    return id;
  }

  /**
   * set id.
   * 
   * @param id id
   */
  public void setId(long id) {
    this.id = id;
  }

  /**
   * get skuNumber.
   * 
   * @return skuNumber
   */
  public String getSkuNumber() {
    return skuNumber;
  }

  /**
   * set skuNumber.
   * 
   * @param skuNumber skuNumber
   */
  public void setSkuNumber(String skuNumber) {
    this.skuNumber = skuNumber;
  }

  /**
   * get active.
   * 
   * @return active
   */
  public boolean isActive() {
    return active;
  }

  /**
   * set active.
   * 
   * @param active active
   */
  public void setActive(boolean active) {
    this.active = active;
  }

  /**
   * get quantity.
   * 
   * @return quantity
   */
  public int getQuantity() {
    return quantity;
  }

  /**
   * set quantity.
   * 
   * @param quantity quantity
   */
  public void setQuantity(int quantity) {
    this.quantity = quantity;
  }

  /**
   * get upc.
   * 
   * @return upc
   */
  public String getUpc() {
    return upc;
  }

  /**
   * set upd.
   * 
   * @param upc upc
   */
  public void setUpc(String upc) {
    this.upc = upc;
  }

  /**
   * get displayOrder.
   * 
   * @return displayOrder
   */
  public int getDisplayOrder() {
    return displayOrder;
  }

  /**
   * set displayOrder.
   * 
   * @param displayOrder displayOrder
   */
  public void setDisplayOrder(int displayOrder) {
    this.displayOrder = displayOrder;
  }

  /**
   * get medias.
   * 
   * @return medias.
   */
  public Set<Media> getMedias() {
    return medias;
  }

  /**
   * set medias.
   * 
   * @param medias medias
   */
  public void setMedias(Set<Media> medias) {
    this.medias = medias;
  }

  /**
   * get variantValues.
   * 
   * @return variantValues
   */
  public Set<VariantValue> getVariantValues() {
    return variantValues;
  }

  /**
   * set variantValues.
   * 
   * @param variantValues variantValues
   */
  public void setVariantValues(Set<VariantValue> variantValues) {
    this.variantValues = variantValues;
  }

  /**
   * get createTime.
   * 
   * @return createTime
   */
  public Date getCreateTime() {
    return new Date(createTime.getTime());
  }

  /**
   * set createTime.
   * 
   * @param createTime createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = new Date(createTime.getTime());
  }

  /**
   * get lastModifiedTime.
   * 
   * @return lastModifiedTime
   */
  public Date getLastModifiedTime() {
    return new Date(lastModifiedTime.getTime());
  }

  /**
   * set lastModifiedTime.
   * 
   * @param lastModifiedTime lastModifiedTime
   */
  public void setLastModifiedTime(Date lastModifiedTime) {
    this.lastModifiedTime = new Date(lastModifiedTime.getTime());
  }

  /**
   * get product.
   * 
   * @return product
   */
  public Product getProduct() {
    return product;
  }

  /**
   * set product.
   * 
   * @param product product
   */
  public void setProduct(Product product) {
    this.product = product;
  }

  /**
   * get price.
   * 
   * @return price
   */
  public BigDecimal getPrice() {
    return price;
  }

  /**
   * set price.
   * 
   * @param price price
   */
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   * hashCode.
   */
  @Override
  public int hashCode() {
    return Objects.hash(id, skuNumber, active, quantity, upc, displayOrder);
  }

  /**
   * equals.
   */
  @Override
  public boolean equals(Object obj) {
    boolean equalsResult = false;
    if (this == obj) {
      equalsResult = true;
    } else if (obj instanceof Sku) {
      final Sku other = (Sku) obj;
      equalsResult = Objects.equals(id, other.id) && Objects.equals(skuNumber, other.skuNumber)
          && Objects.equals(active, other.active) && Objects.equals(quantity, other.quantity)
          && Objects.equals(upc, other.upc) && Objects.equals(displayOrder, other.displayOrder);
    }
    return equalsResult;
  }
}
