// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog-message.proto

package io.reactivesw.catalog.infrastructure;

public interface CategoryListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.CategoryList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory category = 1;</code>
   */
  java.util.List<io.reactivesw.catalog.infrastructure.GrpcCategory> 
      getCategoryList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory category = 1;</code>
   */
  io.reactivesw.catalog.infrastructure.GrpcCategory getCategory(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory category = 1;</code>
   */
  int getCategoryCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory category = 1;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.infrastructure.GrpcCategoryOrBuilder> 
      getCategoryOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory category = 1;</code>
   */
  io.reactivesw.catalog.infrastructure.GrpcCategoryOrBuilder getCategoryOrBuilder(
      int index);
}
