// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog-message.proto

package io.reactivesw.catalog.infrastructure;

public interface GrpcCategoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.GrpcCategory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional int32 displayOrder = 4;</code>
   */
  int getDisplayOrder();

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory sub_category = 5;</code>
   */
  java.util.List<io.reactivesw.catalog.infrastructure.GrpcCategory> 
      getSubCategoryList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory sub_category = 5;</code>
   */
  io.reactivesw.catalog.infrastructure.GrpcCategory getSubCategory(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory sub_category = 5;</code>
   */
  int getSubCategoryCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory sub_category = 5;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.infrastructure.GrpcCategoryOrBuilder> 
      getSubCategoryOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcCategory sub_category = 5;</code>
   */
  io.reactivesw.catalog.infrastructure.GrpcCategoryOrBuilder getSubCategoryOrBuilder(
      int index);
}
