package io.reactivesw.catalog.domain.entity;

import com.google.common.base.Objects;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * this is the entity class for attribute.
 * @author Davis
 */
@Entity
@Table(name = "sw_attribute")
public class Attribute implements Serializable {

  /**
   * serialVersionUID.
   */
  private static final long serialVersionUID = 1484026985124513749L;

  /**
   * id for attribute. auto generated by database.
   */
  @Id
  @Column(name = "attribute_id")
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  /**
   * name for attribute. max length is 64. the field conn't be null.
   */
  @Size(max = 64)
  @Column(name = "name", length = 64, nullable = false)
  private String name;

  /**
   * description for attribute. max length is 1024. description can be null.
   */
  @Size(max = 1024)
  @Column(name = "description", length = 1024)
  private String description;

  /**
   * type for attribute.
   */
  @Size(max = 16)
  @Column(name = "type", length = 16, nullable = false)
  private String type;

  /**
   * display order for attribute.
   */
  @Column(name = "display_order")
  private int displayOrder;

  /**
   * create time for product.
   */
  @Column(name = "created_time")
  private ZonedDateTime createdTime;

  /**
   * last modified time for product.
   */
  @Column(name = "modified_time")
  private ZonedDateTime modifiedTime;

  /**
   * attribute values.
   */
  @OneToMany(mappedBy = "attribute", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
  private Set<AttributeValue> attributeValues;

  /**
   * get id.
   * @return the id
   */
  public long getId() {
    return id;
  }

  /**
   * set id.
   * @param id the id to set
   */
  public void setId(long id) {
    this.id = id;
  }

  /**
   * get name.
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * set name.
   * @param name the name to set
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * get description.
   * @return the description
   */
  public String getDescription() {
    return description;
  }

  /**
   * set description.
   * @param description the description to set
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * get type.
   * @return the type
   */
  public String getType() {
    return type;
  }

  /**
   * set type.
   * @param type the type to set
   */
  public void setType(String type) {
    this.type = type;
  }

  /**
   * get displayOrder.
   * @return the displayOrder
   */
  public int getDisplayOrder() {
    return displayOrder;
  }

  /**
   * set displayOrder.
   * @param displayOrder the displayOrder to set
   */
  public void setDisplayOrder(int displayOrder) {
    this.displayOrder = displayOrder;
  }

  /**
   * get createdTime.
   *
   * @return createdTime
   */
  public ZonedDateTime getCreatedTime() {
    return createdTime;
  }

  /**
   * set createdTime.
   *
   * @param createdTime createdTime
   */
  public void setCreatedTime(ZonedDateTime createdTime) {
    this.createdTime = createdTime;
  }

  /**
   * get lastModifiedTiem.
   *
   * @return lastModifiedTiem
   */
  public ZonedDateTime getModifiedTime() {
    return modifiedTime;
  }

  /**
   * set modifiedTime.
   *
   * @param modifiedTime the modifiedTime to set
   */
  public void setModifiedTime(ZonedDateTime modifiedTime) {
    this.modifiedTime = modifiedTime;
  }


  /**
   * get attribute values.
   * @return the attributeValues
   */
  public Set<AttributeValue> getAttributeValues() {
    return attributeValues;
  }

  /**
   * set attribute values.
   * @param attributeValues the attributeValues to set
   */
  public void setAttributeValues(Set<AttributeValue> attributeValues) {
    this.attributeValues = attributeValues;
  }

  /**
   * hashCode.
   */
  @Override
  public int hashCode() {
    return Objects.hashCode(id, name, description, type, displayOrder);
  }

  /**
   * equals.
   */
  @Override
  public boolean equals(Object obj) {
    boolean equalsResult = false;
    if (this == obj) {
      equalsResult = true;
    } else if (obj instanceof Attribute) {
      final Attribute other = (Attribute) obj;
      equalsResult = Objects.equal(id, other.id) && Objects.equal(name, other.name)
          && Objects.equal(description, other.description) && Objects.equal(type, other.type)
          && Objects.equal(displayOrder, other.displayOrder);
    }
    return equalsResult;
  }
}
