package io.reactivesw.catalog.domain.entity;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * this is entity class for template.
 * 
 * @author Davis
 *
 */
@Entity
@Table(name = "sw_template")
public class Template implements Serializable {

  /**
   * serialVersionUID.
   */
  private static final long serialVersionUID = -366232774085816005L;

  /**
   * id for template. auto generated by database.
   */
  @Id
  @Column(name = "template_id")
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  /**
   * name for template.
   */
  @Size(max = 64)
  @Column(name = "name", length = 64, nullable = false)
  private String name;

  /**
   * description for template.
   */
  @Size(max = 1024)
  @Column(name = "description", length = 1024)
  private String description;

  /**
   * attributes for template.
   */
  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
  @JoinTable(name = "sw_template_attribute", joinColumns = @JoinColumn(name = "template_id") ,
      inverseJoinColumns = @JoinColumn(name = "attribute_id") )
  private Set<Attribute> attributes;

  /**
   * create time.
   */
  @Column(name = "created_time")
  private ZonedDateTime createdTime;

  /**
   * last modified time.
   */
  @Column(name = "modified_time")
  private ZonedDateTime modifiedTime;

  /**
   * products for template.
   */
  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
  private Set<Product> products;

  /**
   * get id.
   * 
   * @return the id
   */
  public long getId() {
    return id;
  }

  /**
   * set id.
   * 
   * @param id the id to set
   */
  public void setId(long id) {
    this.id = id;
  }

  /**
   * get name.
   * 
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * set name.
   * 
   * @param name the name to set
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * get description.
   * 
   * @return the description
   */
  public String getDescription() {
    return description;
  }

  /**
   * set description.
   * 
   * @param description the description to set
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * get attributes.
   * 
   * @return the attributes
   */
  public Set<Attribute> getAttributes() {
    return attributes;
  }

  /**
   * set attributes.
   * 
   * @param attributes the attributes to set
   */
  public void setAttributes(Set<Attribute> attributes) {
    this.attributes = attributes;
  }

  /**
   * get create time.
   *
   * @return create time.
   */
  public ZonedDateTime getCreatedTime() {
    return createdTime;
  }

  /**
   * set create time.
   *
   * @param createdTime create time.
   */
  public void setCreatedTime(ZonedDateTime createdTime) {
    this.createdTime = createdTime;
  }

  /**
   * get last modified time.
   *
   * @return modifiedTime.
   */
  public ZonedDateTime getModifiedTime() {
    return modifiedTime;
  }

  /**
   * set last modified time.
   *
   * @param modifiedTime last modified time.
   */
  public void setModifiedTime(ZonedDateTime modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  /**
   * get products.
   * 
   * @return the products
   */
  public Set<Product> getProducts() {
    return products;
  }

  /**
   * set products.
   * 
   * @param products the products to set
   */
  public void setProducts(Set<Product> products) {
    this.products = products;
  }

  /**
   * hashCode.
   */
  @Override
  public int hashCode() {
    return Objects.hash(id, name, description);
  }

  /**
   * equals.
   */
  @Override
  public boolean equals(Object obj) {
    boolean equalsResult = false;
    if (this == obj) {
      equalsResult = true;
    } else if (obj instanceof Template) {
      final Template other = (Template) obj;
      equalsResult = Objects.equals(id, other.id) && Objects.equals(name, other.name)
          && Objects.equals(description, other.description);
    }
    return equalsResult;
  }
}
