// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catelog-message.proto

package io.reactivesw.catelog.infrastructure;

public final class CatelogMessage {
  private CatelogMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_CategoryList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_CategoryList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcCategory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_ProductBriefList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_ProductBriefList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcProductBrief_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcProductBrief_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_FeatureList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_FeatureList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcFeature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcFeature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_VariantList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_VariantList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcVariant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcVariant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcVariantValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcVariantValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_SkuList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_SkuList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcSku_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcSku_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcMedia_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcMedia_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_AttributeList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_AttributeList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_reactivesw_catelog_infrastructure_GrpcAttribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_reactivesw_catelog_infrastructure_GrpcAttribute_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025catelog-message.proto\022$io.reactivesw.c" +
      "atelog.infrastructure\"T\n\014CategoryList\022D\n" +
      "\010category\030\001 \003(\01322.io.reactivesw.catelog." +
      "infrastructure.GrpcCategory\"\241\001\n\014GrpcCate" +
      "gory\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013descri" +
      "ption\030\003 \001(\t\022\024\n\014displayOrder\030\004 \001(\005\022L\n\020sub" +
      "CategoryInfos\030\005 \003(\01322.io.reactivesw.cate" +
      "log.infrastructure.GrpcCategory\"`\n\020Produ" +
      "ctBriefList\022L\n\014productBrief\030\003 \003(\01326.io.r" +
      "eactivesw.catelog.infrastructure.GrpcPro",
      "ductBrief\"c\n\020GrpcProductBrief\022\n\n\002id\030\001 \001(" +
      "\003\022\014\n\004name\030\002 \001(\t\022\r\n\005price\030\003 \001(\t\022\024\n\014displa" +
      "yOrder\030\004 \001(\005\022\020\n\010mediaURL\030\005 \001(\t\"\275\001\n\013GrpcP" +
      "roduct\022\n\n\002id\030\001 \001(\003\022\024\n\014manufacturer\030\002 \001(\t" +
      "\022\r\n\005brand\030\003 \001(\t\022\r\n\005model\030\004 \001(\t\022\014\n\004name\030\005" +
      " \001(\t\022\r\n\005price\030\006 \001(\t\022\024\n\014displayOrder\030\007 \001(" +
      "\005\022\023\n\013description\030\010 \001(\t\022\023\n\013isDisplayed\030\n " +
      "\001(\010\022\021\n\tisDeleted\030\013 \001(\010\"Q\n\013FeatureList\022B\n" +
      "\007feature\030\001 \003(\01321.io.reactivesw.catelog.i" +
      "nfrastructure.GrpcFeature\"R\n\013GrpcFeature",
      "\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013descriptio" +
      "n\030\003 \001(\t\022\024\n\014displayOrder\030\004 \001(\005\"Q\n\013Variant" +
      "List\022B\n\007variant\030\001 \003(\01321.io.reactivesw.ca" +
      "telog.infrastructure.GrpcVariant\"\213\001\n\013Grp" +
      "cVariant\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\024\n\014di" +
      "splayOrder\030\003 \001(\005\022L\n\014variantValue\030\004 \003(\01326" +
      ".io.reactivesw.catelog.infrastructure.Gr" +
      "pcVariantValue\"\\\n\020GrpcVariantValue\022\n\n\002id" +
      "\030\001 \001(\003\022\r\n\005value\030\002 \001(\t\022\024\n\014displayOrder\030\003 " +
      "\001(\005\022\027\n\017priceAdjustment\030\004 \001(\t\"E\n\007SkuList\022",
      ":\n\003sku\030\001 \003(\0132-.io.reactivesw.catelog.inf" +
      "rastructure.GrpcSku\"\374\001\n\007GrpcSku\022\n\n\002id\030\001 " +
      "\001(\003\022\021\n\tskuNumber\030\002 \001(\t\022\020\n\010isActive\030\003 \001(\010" +
      "\022\017\n\007quatity\030\004 \001(\005\022\013\n\003upc\030\005 \001(\t\022\024\n\014displa" +
      "yOrder\030\006 \001(\005\022>\n\005media\030\007 \003(\0132/.io.reactiv" +
      "esw.catelog.infrastructure.GrpcMedia\022L\n\014" +
      "variantValue\030\010 \003(\01326.io.reactivesw.catel" +
      "og.infrastructure.GrpcVariantValue\"W\n\tGr" +
      "pcMedia\022\n\n\002id\030\001 \001(\003\022\014\n\004type\030\002 \001(\t\022\r\n\005tit" +
      "le\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\022\024\n\014displayOrder\030\005 ",
      "\001(\005\"W\n\rAttributeList\022F\n\tattribute\030\001 \003(\0132" +
      "3.io.reactivesw.catelog.infrastructure.G" +
      "rpcAttribute\"q\n\rGrpcAttribute\022\n\n\002id\030\001 \001(" +
      "\003\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\r\n\005" +
      "value\030\004 \001(\t\022\014\n\004type\030\005 \001(\t\022\024\n\014displayOrde" +
      "r\030\006 \001(\005B+\n$io.reactivesw.catelog.infrast" +
      "ructureP\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_reactivesw_catelog_infrastructure_CategoryList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_reactivesw_catelog_infrastructure_CategoryList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_CategoryList_descriptor,
        new java.lang.String[] { "Category", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcCategory_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcCategory_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "DisplayOrder", "SubCategoryInfos", });
    internal_static_io_reactivesw_catelog_infrastructure_ProductBriefList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_reactivesw_catelog_infrastructure_ProductBriefList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_ProductBriefList_descriptor,
        new java.lang.String[] { "ProductBrief", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcProductBrief_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcProductBrief_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcProductBrief_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", "DisplayOrder", "MediaURL", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcProduct_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcProduct_descriptor,
        new java.lang.String[] { "Id", "Manufacturer", "Brand", "Model", "Name", "Price", "DisplayOrder", "Description", "IsDisplayed", "IsDeleted", });
    internal_static_io_reactivesw_catelog_infrastructure_FeatureList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_io_reactivesw_catelog_infrastructure_FeatureList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_FeatureList_descriptor,
        new java.lang.String[] { "Feature", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcFeature_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcFeature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcFeature_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "DisplayOrder", });
    internal_static_io_reactivesw_catelog_infrastructure_VariantList_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_io_reactivesw_catelog_infrastructure_VariantList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_VariantList_descriptor,
        new java.lang.String[] { "Variant", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcVariant_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcVariant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcVariant_descriptor,
        new java.lang.String[] { "Id", "Name", "DisplayOrder", "VariantValue", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcVariantValue_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcVariantValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcVariantValue_descriptor,
        new java.lang.String[] { "Id", "Value", "DisplayOrder", "PriceAdjustment", });
    internal_static_io_reactivesw_catelog_infrastructure_SkuList_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_io_reactivesw_catelog_infrastructure_SkuList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_SkuList_descriptor,
        new java.lang.String[] { "Sku", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcSku_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcSku_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcSku_descriptor,
        new java.lang.String[] { "Id", "SkuNumber", "IsActive", "Quatity", "Upc", "DisplayOrder", "Media", "VariantValue", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcMedia_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcMedia_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcMedia_descriptor,
        new java.lang.String[] { "Id", "Type", "Title", "Url", "DisplayOrder", });
    internal_static_io_reactivesw_catelog_infrastructure_AttributeList_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_io_reactivesw_catelog_infrastructure_AttributeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_AttributeList_descriptor,
        new java.lang.String[] { "Attribute", });
    internal_static_io_reactivesw_catelog_infrastructure_GrpcAttribute_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_io_reactivesw_catelog_infrastructure_GrpcAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_reactivesw_catelog_infrastructure_GrpcAttribute_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Value", "Type", "DisplayOrder", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
