// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catelog-service.proto

package io.reactivesw.catelog.infrastructure;

public final class CatelogService {
  private CatelogService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025catelog-service.proto\022$io.reactivesw.c" +
      "atelog.infrastructure\032\033google/protobuf/e" +
      "mpty.proto\032\036google/protobuf/wrappers.pro" +
      "to\032\025catelog-message.proto2n\n\017CategorySer" +
      "vice\022[\n\rgetCategories\022\026.google.protobuf." +
      "Empty\0322.io.reactivesw.catelog.infrastruc" +
      "ture.CategoryList2\342\001\n\016ProductService\022l\n\025" +
      "getProductsByCategory\022\033.google.protobuf." +
      "Int64Value\0326.io.reactivesw.catelog.infra" +
      "structure.ProductBriefList\022b\n\020getProduct",
      "Detial\022\033.google.protobuf.Int64Value\0321.io" +
      ".reactivesw.catelog.infrastructure.GrpcP" +
      "roductB(\n$io.reactivesw.catelog.infrastr" +
      "uctureP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          io.reactivesw.catelog.infrastructure.CatelogMessage.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    io.reactivesw.catelog.infrastructure.CatelogMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
