// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catelog-message.proto

package io.reactivesw.catelog.infrastructure;

/**
 * <pre>
 **
 * response when call getProductFeature.
 * </pre>
 *
 * Protobuf type {@code io.reactivesw.catelog.infrastructure.FeatureList}
 */
public  final class FeatureList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catelog.infrastructure.FeatureList)
    FeatureListOrBuilder {
  // Use FeatureList.newBuilder() to construct.
  private FeatureList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FeatureList() {
    feature_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FeatureList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              feature_ = new java.util.ArrayList<io.reactivesw.catelog.infrastructure.GrpcFeature>();
              mutable_bitField0_ |= 0x00000001;
            }
            feature_.add(input.readMessage(io.reactivesw.catelog.infrastructure.GrpcFeature.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        feature_ = java.util.Collections.unmodifiableList(feature_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_FeatureList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_FeatureList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catelog.infrastructure.FeatureList.class, io.reactivesw.catelog.infrastructure.FeatureList.Builder.class);
  }

  public static final int FEATURE_FIELD_NUMBER = 1;
  private java.util.List<io.reactivesw.catelog.infrastructure.GrpcFeature> feature_;
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  public java.util.List<io.reactivesw.catelog.infrastructure.GrpcFeature> getFeatureList() {
    return feature_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  public java.util.List<? extends io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder> 
      getFeatureOrBuilderList() {
    return feature_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  public int getFeatureCount() {
    return feature_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  public io.reactivesw.catelog.infrastructure.GrpcFeature getFeature(int index) {
    return feature_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  public io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder getFeatureOrBuilder(
      int index) {
    return feature_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < feature_.size(); i++) {
      output.writeMessage(1, feature_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < feature_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, feature_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.catelog.infrastructure.FeatureList)) {
      return super.equals(obj);
    }
    io.reactivesw.catelog.infrastructure.FeatureList other = (io.reactivesw.catelog.infrastructure.FeatureList) obj;

    boolean result = true;
    result = result && getFeatureList()
        .equals(other.getFeatureList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getFeatureCount() > 0) {
      hash = (37 * hash) + FEATURE_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.catelog.infrastructure.FeatureList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.FeatureList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catelog.infrastructure.FeatureList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * response when call getProductFeature.
   * </pre>
   *
   * Protobuf type {@code io.reactivesw.catelog.infrastructure.FeatureList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catelog.infrastructure.FeatureList)
      io.reactivesw.catelog.infrastructure.FeatureListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_FeatureList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_FeatureList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catelog.infrastructure.FeatureList.class, io.reactivesw.catelog.infrastructure.FeatureList.Builder.class);
    }

    // Construct using io.reactivesw.catelog.infrastructure.FeatureList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getFeatureFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (featureBuilder_ == null) {
        feature_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        featureBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_FeatureList_descriptor;
    }

    public io.reactivesw.catelog.infrastructure.FeatureList getDefaultInstanceForType() {
      return io.reactivesw.catelog.infrastructure.FeatureList.getDefaultInstance();
    }

    public io.reactivesw.catelog.infrastructure.FeatureList build() {
      io.reactivesw.catelog.infrastructure.FeatureList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catelog.infrastructure.FeatureList buildPartial() {
      io.reactivesw.catelog.infrastructure.FeatureList result = new io.reactivesw.catelog.infrastructure.FeatureList(this);
      int from_bitField0_ = bitField0_;
      if (featureBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          feature_ = java.util.Collections.unmodifiableList(feature_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.feature_ = feature_;
      } else {
        result.feature_ = featureBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catelog.infrastructure.FeatureList) {
        return mergeFrom((io.reactivesw.catelog.infrastructure.FeatureList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catelog.infrastructure.FeatureList other) {
      if (other == io.reactivesw.catelog.infrastructure.FeatureList.getDefaultInstance()) return this;
      if (featureBuilder_ == null) {
        if (!other.feature_.isEmpty()) {
          if (feature_.isEmpty()) {
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFeatureIsMutable();
            feature_.addAll(other.feature_);
          }
          onChanged();
        }
      } else {
        if (!other.feature_.isEmpty()) {
          if (featureBuilder_.isEmpty()) {
            featureBuilder_.dispose();
            featureBuilder_ = null;
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00000001);
            featureBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getFeatureFieldBuilder() : null;
          } else {
            featureBuilder_.addAllMessages(other.feature_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catelog.infrastructure.FeatureList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catelog.infrastructure.FeatureList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.reactivesw.catelog.infrastructure.GrpcFeature> feature_ =
      java.util.Collections.emptyList();
    private void ensureFeatureIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        feature_ = new java.util.ArrayList<io.reactivesw.catelog.infrastructure.GrpcFeature>(feature_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.infrastructure.GrpcFeature, io.reactivesw.catelog.infrastructure.GrpcFeature.Builder, io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder> featureBuilder_;

    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public java.util.List<io.reactivesw.catelog.infrastructure.GrpcFeature> getFeatureList() {
      if (featureBuilder_ == null) {
        return java.util.Collections.unmodifiableList(feature_);
      } else {
        return featureBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public int getFeatureCount() {
      if (featureBuilder_ == null) {
        return feature_.size();
      } else {
        return featureBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcFeature getFeature(int index) {
      if (featureBuilder_ == null) {
        return feature_.get(index);
      } else {
        return featureBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder setFeature(
        int index, io.reactivesw.catelog.infrastructure.GrpcFeature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.set(index, value);
        onChanged();
      } else {
        featureBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder setFeature(
        int index, io.reactivesw.catelog.infrastructure.GrpcFeature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.set(index, builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder addFeature(io.reactivesw.catelog.infrastructure.GrpcFeature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
      } else {
        featureBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder addFeature(
        int index, io.reactivesw.catelog.infrastructure.GrpcFeature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.add(index, value);
        onChanged();
      } else {
        featureBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder addFeature(
        io.reactivesw.catelog.infrastructure.GrpcFeature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.add(builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder addFeature(
        int index, io.reactivesw.catelog.infrastructure.GrpcFeature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.add(index, builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder addAllFeature(
        java.lang.Iterable<? extends io.reactivesw.catelog.infrastructure.GrpcFeature> values) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, feature_);
        onChanged();
      } else {
        featureBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder clearFeature() {
      if (featureBuilder_ == null) {
        feature_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        featureBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public Builder removeFeature(int index) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.remove(index);
        onChanged();
      } else {
        featureBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcFeature.Builder getFeatureBuilder(
        int index) {
      return getFeatureFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder getFeatureOrBuilder(
        int index) {
      if (featureBuilder_ == null) {
        return feature_.get(index);  } else {
        return featureBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public java.util.List<? extends io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder> 
         getFeatureOrBuilderList() {
      if (featureBuilder_ != null) {
        return featureBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(feature_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcFeature.Builder addFeatureBuilder() {
      return getFeatureFieldBuilder().addBuilder(
          io.reactivesw.catelog.infrastructure.GrpcFeature.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcFeature.Builder addFeatureBuilder(
        int index) {
      return getFeatureFieldBuilder().addBuilder(
          index, io.reactivesw.catelog.infrastructure.GrpcFeature.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
     */
    public java.util.List<io.reactivesw.catelog.infrastructure.GrpcFeature.Builder> 
         getFeatureBuilderList() {
      return getFeatureFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.infrastructure.GrpcFeature, io.reactivesw.catelog.infrastructure.GrpcFeature.Builder, io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder> 
        getFeatureFieldBuilder() {
      if (featureBuilder_ == null) {
        featureBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.reactivesw.catelog.infrastructure.GrpcFeature, io.reactivesw.catelog.infrastructure.GrpcFeature.Builder, io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder>(
                feature_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        feature_ = null;
      }
      return featureBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catelog.infrastructure.FeatureList)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catelog.infrastructure.FeatureList)
  private static final io.reactivesw.catelog.infrastructure.FeatureList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catelog.infrastructure.FeatureList();
  }

  public static io.reactivesw.catelog.infrastructure.FeatureList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeatureList>
      PARSER = new com.google.protobuf.AbstractParser<FeatureList>() {
    public FeatureList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeatureList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FeatureList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeatureList> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catelog.infrastructure.FeatureList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

