// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catelog-message.proto

package io.reactivesw.catelog.infrastructure;

public interface FeatureListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.infrastructure.FeatureList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  java.util.List<io.reactivesw.catelog.infrastructure.GrpcFeature> 
      getFeatureList();
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  io.reactivesw.catelog.infrastructure.GrpcFeature getFeature(int index);
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  java.util.List<? extends io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcFeature feature = 1;</code>
   */
  io.reactivesw.catelog.infrastructure.GrpcFeatureOrBuilder getFeatureOrBuilder(
      int index);
}
