// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.infrastructure;

/**
 * Protobuf type {@code io.reactivesw.catelog.grpc.GrpcCategory}
 */
public  final class GrpcCategory extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catelog.grpc.GrpcCategory)
    GrpcCategoryOrBuilder {
  // Use GrpcCategory.newBuilder() to construct.
  private GrpcCategory(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GrpcCategory() {
    id_ = 0L;
    name_ = "";
    description_ = "";
    displayOrder_ = 0;
    subCategoryInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GrpcCategory(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 32: {

            displayOrder_ = input.readInt32();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              subCategoryInfos_ = new java.util.ArrayList<io.reactivesw.catelog.infrastructure.GrpcCategory>();
              mutable_bitField0_ |= 0x00000010;
            }
            subCategoryInfos_.add(input.readMessage(io.reactivesw.catelog.infrastructure.GrpcCategory.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        subCategoryInfos_ = java.util.Collections.unmodifiableList(subCategoryInfos_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catelog.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_GrpcCategory_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catelog.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_GrpcCategory_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catelog.infrastructure.GrpcCategory.class, io.reactivesw.catelog.infrastructure.GrpcCategory.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>optional string description = 3;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>optional string description = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYORDER_FIELD_NUMBER = 4;
  private int displayOrder_;
  /**
   * <code>optional int32 displayOrder = 4;</code>
   */
  public int getDisplayOrder() {
    return displayOrder_;
  }

  public static final int SUBCATEGORYINFOS_FIELD_NUMBER = 5;
  private java.util.List<io.reactivesw.catelog.infrastructure.GrpcCategory> subCategoryInfos_;
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
   */
  public java.util.List<io.reactivesw.catelog.infrastructure.GrpcCategory> getSubCategoryInfosList() {
    return subCategoryInfos_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
   */
  public java.util.List<? extends io.reactivesw.catelog.infrastructure.GrpcCategoryOrBuilder> 
      getSubCategoryInfosOrBuilderList() {
    return subCategoryInfos_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
   */
  public int getSubCategoryInfosCount() {
    return subCategoryInfos_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
   */
  public io.reactivesw.catelog.infrastructure.GrpcCategory getSubCategoryInfos(int index) {
    return subCategoryInfos_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
   */
  public io.reactivesw.catelog.infrastructure.GrpcCategoryOrBuilder getSubCategoryInfosOrBuilder(
      int index) {
    return subCategoryInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
    }
    if (displayOrder_ != 0) {
      output.writeInt32(4, displayOrder_);
    }
    for (int i = 0; i < subCategoryInfos_.size(); i++) {
      output.writeMessage(5, subCategoryInfos_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
    }
    if (displayOrder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, displayOrder_);
    }
    for (int i = 0; i < subCategoryInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, subCategoryInfos_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.GrpcCategory parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catelog.infrastructure.GrpcCategory prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.reactivesw.catelog.grpc.GrpcCategory}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catelog.grpc.GrpcCategory)
      io.reactivesw.catelog.infrastructure.GrpcCategoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catelog.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_GrpcCategory_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catelog.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_GrpcCategory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catelog.infrastructure.GrpcCategory.class, io.reactivesw.catelog.infrastructure.GrpcCategory.Builder.class);
    }

    // Construct using io.reactivesw.catelog.infrastructure.GrpcCategory.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getSubCategoryInfosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      description_ = "";

      displayOrder_ = 0;

      if (subCategoryInfosBuilder_ == null) {
        subCategoryInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        subCategoryInfosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catelog.infrastructure.ReactiveswCatelog.internal_static_io_reactivesw_catelog_grpc_GrpcCategory_descriptor;
    }

    public io.reactivesw.catelog.infrastructure.GrpcCategory getDefaultInstanceForType() {
      return io.reactivesw.catelog.infrastructure.GrpcCategory.getDefaultInstance();
    }

    public io.reactivesw.catelog.infrastructure.GrpcCategory build() {
      io.reactivesw.catelog.infrastructure.GrpcCategory result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catelog.infrastructure.GrpcCategory buildPartial() {
      io.reactivesw.catelog.infrastructure.GrpcCategory result = new io.reactivesw.catelog.infrastructure.GrpcCategory(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.description_ = description_;
      result.displayOrder_ = displayOrder_;
      if (subCategoryInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          subCategoryInfos_ = java.util.Collections.unmodifiableList(subCategoryInfos_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.subCategoryInfos_ = subCategoryInfos_;
      } else {
        result.subCategoryInfos_ = subCategoryInfosBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catelog.infrastructure.GrpcCategory) {
        return mergeFrom((io.reactivesw.catelog.infrastructure.GrpcCategory)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catelog.infrastructure.GrpcCategory other) {
      if (other == io.reactivesw.catelog.infrastructure.GrpcCategory.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getDisplayOrder() != 0) {
        setDisplayOrder(other.getDisplayOrder());
      }
      if (subCategoryInfosBuilder_ == null) {
        if (!other.subCategoryInfos_.isEmpty()) {
          if (subCategoryInfos_.isEmpty()) {
            subCategoryInfos_ = other.subCategoryInfos_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSubCategoryInfosIsMutable();
            subCategoryInfos_.addAll(other.subCategoryInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.subCategoryInfos_.isEmpty()) {
          if (subCategoryInfosBuilder_.isEmpty()) {
            subCategoryInfosBuilder_.dispose();
            subCategoryInfosBuilder_ = null;
            subCategoryInfos_ = other.subCategoryInfos_;
            bitField0_ = (bitField0_ & ~0x00000010);
            subCategoryInfosBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSubCategoryInfosFieldBuilder() : null;
          } else {
            subCategoryInfosBuilder_.addAllMessages(other.subCategoryInfos_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catelog.infrastructure.GrpcCategory parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catelog.infrastructure.GrpcCategory) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>optional string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private int displayOrder_ ;
    /**
     * <code>optional int32 displayOrder = 4;</code>
     */
    public int getDisplayOrder() {
      return displayOrder_;
    }
    /**
     * <code>optional int32 displayOrder = 4;</code>
     */
    public Builder setDisplayOrder(int value) {
      
      displayOrder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 displayOrder = 4;</code>
     */
    public Builder clearDisplayOrder() {
      
      displayOrder_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<io.reactivesw.catelog.infrastructure.GrpcCategory> subCategoryInfos_ =
      java.util.Collections.emptyList();
    private void ensureSubCategoryInfosIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        subCategoryInfos_ = new java.util.ArrayList<io.reactivesw.catelog.infrastructure.GrpcCategory>(subCategoryInfos_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.infrastructure.GrpcCategory, io.reactivesw.catelog.infrastructure.GrpcCategory.Builder, io.reactivesw.catelog.infrastructure.GrpcCategoryOrBuilder> subCategoryInfosBuilder_;

    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public java.util.List<io.reactivesw.catelog.infrastructure.GrpcCategory> getSubCategoryInfosList() {
      if (subCategoryInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subCategoryInfos_);
      } else {
        return subCategoryInfosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public int getSubCategoryInfosCount() {
      if (subCategoryInfosBuilder_ == null) {
        return subCategoryInfos_.size();
      } else {
        return subCategoryInfosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcCategory getSubCategoryInfos(int index) {
      if (subCategoryInfosBuilder_ == null) {
        return subCategoryInfos_.get(index);
      } else {
        return subCategoryInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder setSubCategoryInfos(
        int index, io.reactivesw.catelog.infrastructure.GrpcCategory value) {
      if (subCategoryInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubCategoryInfosIsMutable();
        subCategoryInfos_.set(index, value);
        onChanged();
      } else {
        subCategoryInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder setSubCategoryInfos(
        int index, io.reactivesw.catelog.infrastructure.GrpcCategory.Builder builderForValue) {
      if (subCategoryInfosBuilder_ == null) {
        ensureSubCategoryInfosIsMutable();
        subCategoryInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        subCategoryInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder addSubCategoryInfos(io.reactivesw.catelog.infrastructure.GrpcCategory value) {
      if (subCategoryInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubCategoryInfosIsMutable();
        subCategoryInfos_.add(value);
        onChanged();
      } else {
        subCategoryInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder addSubCategoryInfos(
        int index, io.reactivesw.catelog.infrastructure.GrpcCategory value) {
      if (subCategoryInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubCategoryInfosIsMutable();
        subCategoryInfos_.add(index, value);
        onChanged();
      } else {
        subCategoryInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder addSubCategoryInfos(
        io.reactivesw.catelog.infrastructure.GrpcCategory.Builder builderForValue) {
      if (subCategoryInfosBuilder_ == null) {
        ensureSubCategoryInfosIsMutable();
        subCategoryInfos_.add(builderForValue.build());
        onChanged();
      } else {
        subCategoryInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder addSubCategoryInfos(
        int index, io.reactivesw.catelog.infrastructure.GrpcCategory.Builder builderForValue) {
      if (subCategoryInfosBuilder_ == null) {
        ensureSubCategoryInfosIsMutable();
        subCategoryInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        subCategoryInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder addAllSubCategoryInfos(
        java.lang.Iterable<? extends io.reactivesw.catelog.infrastructure.GrpcCategory> values) {
      if (subCategoryInfosBuilder_ == null) {
        ensureSubCategoryInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subCategoryInfos_);
        onChanged();
      } else {
        subCategoryInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder clearSubCategoryInfos() {
      if (subCategoryInfosBuilder_ == null) {
        subCategoryInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        subCategoryInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public Builder removeSubCategoryInfos(int index) {
      if (subCategoryInfosBuilder_ == null) {
        ensureSubCategoryInfosIsMutable();
        subCategoryInfos_.remove(index);
        onChanged();
      } else {
        subCategoryInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcCategory.Builder getSubCategoryInfosBuilder(
        int index) {
      return getSubCategoryInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcCategoryOrBuilder getSubCategoryInfosOrBuilder(
        int index) {
      if (subCategoryInfosBuilder_ == null) {
        return subCategoryInfos_.get(index);  } else {
        return subCategoryInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public java.util.List<? extends io.reactivesw.catelog.infrastructure.GrpcCategoryOrBuilder> 
         getSubCategoryInfosOrBuilderList() {
      if (subCategoryInfosBuilder_ != null) {
        return subCategoryInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subCategoryInfos_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcCategory.Builder addSubCategoryInfosBuilder() {
      return getSubCategoryInfosFieldBuilder().addBuilder(
          io.reactivesw.catelog.infrastructure.GrpcCategory.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcCategory.Builder addSubCategoryInfosBuilder(
        int index) {
      return getSubCategoryInfosFieldBuilder().addBuilder(
          index, io.reactivesw.catelog.infrastructure.GrpcCategory.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.grpc.GrpcCategory subCategoryInfos = 5;</code>
     */
    public java.util.List<io.reactivesw.catelog.infrastructure.GrpcCategory.Builder> 
         getSubCategoryInfosBuilderList() {
      return getSubCategoryInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.infrastructure.GrpcCategory, io.reactivesw.catelog.infrastructure.GrpcCategory.Builder, io.reactivesw.catelog.infrastructure.GrpcCategoryOrBuilder> 
        getSubCategoryInfosFieldBuilder() {
      if (subCategoryInfosBuilder_ == null) {
        subCategoryInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.reactivesw.catelog.infrastructure.GrpcCategory, io.reactivesw.catelog.infrastructure.GrpcCategory.Builder, io.reactivesw.catelog.infrastructure.GrpcCategoryOrBuilder>(
                subCategoryInfos_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        subCategoryInfos_ = null;
      }
      return subCategoryInfosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catelog.grpc.GrpcCategory)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catelog.grpc.GrpcCategory)
  private static final io.reactivesw.catelog.infrastructure.GrpcCategory DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catelog.infrastructure.GrpcCategory();
  }

  public static io.reactivesw.catelog.infrastructure.GrpcCategory getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcCategory>
      PARSER = new com.google.protobuf.AbstractParser<GrpcCategory>() {
    public GrpcCategory parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GrpcCategory(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcCategory> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcCategory> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catelog.infrastructure.GrpcCategory getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

