// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catelog-message.proto

package io.reactivesw.catelog.infrastructure;

public interface GrpcProductBriefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.infrastructure.GrpcProductBrief)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string price = 3;</code>
   */
  java.lang.String getPrice();
  /**
   * <code>optional string price = 3;</code>
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>optional int32 displayOrder = 4;</code>
   */
  int getDisplayOrder();

  /**
   * <code>optional string mediaURL = 5;</code>
   */
  java.lang.String getMediaURL();
  /**
   * <code>optional string mediaURL = 5;</code>
   */
  com.google.protobuf.ByteString
      getMediaURLBytes();
}
