// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catelog-message.proto

package io.reactivesw.catelog.infrastructure;

public interface GrpcProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.infrastructure.GrpcProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string manufacturer = 2;</code>
   */
  java.lang.String getManufacturer();
  /**
   * <code>optional string manufacturer = 2;</code>
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>optional string brand = 3;</code>
   */
  java.lang.String getBrand();
  /**
   * <code>optional string brand = 3;</code>
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>optional string model = 4;</code>
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 4;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>optional string name = 5;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 5;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string price = 6;</code>
   */
  java.lang.String getPrice();
  /**
   * <code>optional string price = 6;</code>
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>optional int32 displayOrder = 7;</code>
   */
  int getDisplayOrder();

  /**
   * <code>optional string description = 8;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 8;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional bool isDisplayed = 10;</code>
   */
  boolean getIsDisplayed();

  /**
   * <code>optional bool isDeleted = 11;</code>
   */
  boolean getIsDeleted();
}
