// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.infrastructure;

public interface ProductBriefListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.grpc.ProductBriefList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  java.util.List<io.reactivesw.catelog.infrastructure.ProductBriefInfo> 
      getProductBriefInfoList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  io.reactivesw.catelog.infrastructure.ProductBriefInfo getProductBriefInfo(int index);
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  int getProductBriefInfoCount();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  java.util.List<? extends io.reactivesw.catelog.infrastructure.ProductBriefInfoOrBuilder> 
      getProductBriefInfoOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.ProductBriefInfo productBriefInfo = 3;</code>
   */
  io.reactivesw.catelog.infrastructure.ProductBriefInfoOrBuilder getProductBriefInfoOrBuilder(
      int index);
}
