// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.infrastructure;

public interface ProductBriefListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.grpc.ProductBriefList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcProductBrief productBrief = 3;</code>
   */
  java.util.List<io.reactivesw.catelog.infrastructure.GrpcProductBrief> 
      getProductBriefList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcProductBrief productBrief = 3;</code>
   */
  io.reactivesw.catelog.infrastructure.GrpcProductBrief getProductBrief(int index);
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcProductBrief productBrief = 3;</code>
   */
  int getProductBriefCount();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcProductBrief productBrief = 3;</code>
   */
  java.util.List<? extends io.reactivesw.catelog.infrastructure.GrpcProductBriefOrBuilder> 
      getProductBriefOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.GrpcProductBrief productBrief = 3;</code>
   */
  io.reactivesw.catelog.infrastructure.GrpcProductBriefOrBuilder getProductBriefOrBuilder(
      int index);
}
