// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.infrastructure;

public interface SkuInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.grpc.SkuInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string skuNumber = 2;</code>
   */
  java.lang.String getSkuNumber();
  /**
   * <code>optional string skuNumber = 2;</code>
   */
  com.google.protobuf.ByteString
      getSkuNumberBytes();

  /**
   * <code>optional bool isActive = 3;</code>
   */
  boolean getIsActive();

  /**
   * <code>optional int32 quatity = 4;</code>
   */
  int getQuatity();

  /**
   * <code>optional string upc = 5;</code>
   */
  java.lang.String getUpc();
  /**
   * <code>optional string upc = 5;</code>
   */
  com.google.protobuf.ByteString
      getUpcBytes();

  /**
   * <code>optional int32 displayOrder = 6;</code>
   */
  int getDisplayOrder();

  /**
   * <code>repeated .io.reactivesw.catelog.grpc.MediaInfo media = 7;</code>
   */
  java.util.List<io.reactivesw.catelog.infrastructure.MediaInfo> 
      getMediaList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.MediaInfo media = 7;</code>
   */
  io.reactivesw.catelog.infrastructure.MediaInfo getMedia(int index);
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.MediaInfo media = 7;</code>
   */
  int getMediaCount();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.MediaInfo media = 7;</code>
   */
  java.util.List<? extends io.reactivesw.catelog.infrastructure.MediaInfoOrBuilder> 
      getMediaOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.MediaInfo media = 7;</code>
   */
  io.reactivesw.catelog.infrastructure.MediaInfoOrBuilder getMediaOrBuilder(
      int index);

  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 8;</code>
   */
  java.util.List<io.reactivesw.catelog.infrastructure.VariantValueInfo> 
      getVariantValueList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 8;</code>
   */
  io.reactivesw.catelog.infrastructure.VariantValueInfo getVariantValue(int index);
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 8;</code>
   */
  int getVariantValueCount();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 8;</code>
   */
  java.util.List<? extends io.reactivesw.catelog.infrastructure.VariantValueInfoOrBuilder> 
      getVariantValueOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 8;</code>
   */
  io.reactivesw.catelog.infrastructure.VariantValueInfoOrBuilder getVariantValueOrBuilder(
      int index);
}
