// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catelog-message.proto

package io.reactivesw.catelog.infrastructure;

/**
 * <pre>
 **
 * response when call getSkuByProduct.
 * </pre>
 *
 * Protobuf type {@code io.reactivesw.catelog.infrastructure.SkuList}
 */
public  final class SkuList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catelog.infrastructure.SkuList)
    SkuListOrBuilder {
  // Use SkuList.newBuilder() to construct.
  private SkuList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SkuList() {
    sku_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SkuList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              sku_ = new java.util.ArrayList<io.reactivesw.catelog.infrastructure.GrpcSku>();
              mutable_bitField0_ |= 0x00000001;
            }
            sku_.add(input.readMessage(io.reactivesw.catelog.infrastructure.GrpcSku.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        sku_ = java.util.Collections.unmodifiableList(sku_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_SkuList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_SkuList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catelog.infrastructure.SkuList.class, io.reactivesw.catelog.infrastructure.SkuList.Builder.class);
  }

  public static final int SKU_FIELD_NUMBER = 1;
  private java.util.List<io.reactivesw.catelog.infrastructure.GrpcSku> sku_;
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
   */
  public java.util.List<io.reactivesw.catelog.infrastructure.GrpcSku> getSkuList() {
    return sku_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
   */
  public java.util.List<? extends io.reactivesw.catelog.infrastructure.GrpcSkuOrBuilder> 
      getSkuOrBuilderList() {
    return sku_;
  }
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
   */
  public int getSkuCount() {
    return sku_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
   */
  public io.reactivesw.catelog.infrastructure.GrpcSku getSku(int index) {
    return sku_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
   */
  public io.reactivesw.catelog.infrastructure.GrpcSkuOrBuilder getSkuOrBuilder(
      int index) {
    return sku_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < sku_.size(); i++) {
      output.writeMessage(1, sku_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < sku_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, sku_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.catelog.infrastructure.SkuList)) {
      return super.equals(obj);
    }
    io.reactivesw.catelog.infrastructure.SkuList other = (io.reactivesw.catelog.infrastructure.SkuList) obj;

    boolean result = true;
    result = result && getSkuList()
        .equals(other.getSkuList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getSkuCount() > 0) {
      hash = (37 * hash) + SKU_FIELD_NUMBER;
      hash = (53 * hash) + getSkuList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.catelog.infrastructure.SkuList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catelog.infrastructure.SkuList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catelog.infrastructure.SkuList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * response when call getSkuByProduct.
   * </pre>
   *
   * Protobuf type {@code io.reactivesw.catelog.infrastructure.SkuList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catelog.infrastructure.SkuList)
      io.reactivesw.catelog.infrastructure.SkuListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_SkuList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_SkuList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catelog.infrastructure.SkuList.class, io.reactivesw.catelog.infrastructure.SkuList.Builder.class);
    }

    // Construct using io.reactivesw.catelog.infrastructure.SkuList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getSkuFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (skuBuilder_ == null) {
        sku_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        skuBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catelog.infrastructure.CatelogMessage.internal_static_io_reactivesw_catelog_infrastructure_SkuList_descriptor;
    }

    public io.reactivesw.catelog.infrastructure.SkuList getDefaultInstanceForType() {
      return io.reactivesw.catelog.infrastructure.SkuList.getDefaultInstance();
    }

    public io.reactivesw.catelog.infrastructure.SkuList build() {
      io.reactivesw.catelog.infrastructure.SkuList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catelog.infrastructure.SkuList buildPartial() {
      io.reactivesw.catelog.infrastructure.SkuList result = new io.reactivesw.catelog.infrastructure.SkuList(this);
      int from_bitField0_ = bitField0_;
      if (skuBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          sku_ = java.util.Collections.unmodifiableList(sku_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sku_ = sku_;
      } else {
        result.sku_ = skuBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catelog.infrastructure.SkuList) {
        return mergeFrom((io.reactivesw.catelog.infrastructure.SkuList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catelog.infrastructure.SkuList other) {
      if (other == io.reactivesw.catelog.infrastructure.SkuList.getDefaultInstance()) return this;
      if (skuBuilder_ == null) {
        if (!other.sku_.isEmpty()) {
          if (sku_.isEmpty()) {
            sku_ = other.sku_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkuIsMutable();
            sku_.addAll(other.sku_);
          }
          onChanged();
        }
      } else {
        if (!other.sku_.isEmpty()) {
          if (skuBuilder_.isEmpty()) {
            skuBuilder_.dispose();
            skuBuilder_ = null;
            sku_ = other.sku_;
            bitField0_ = (bitField0_ & ~0x00000001);
            skuBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSkuFieldBuilder() : null;
          } else {
            skuBuilder_.addAllMessages(other.sku_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catelog.infrastructure.SkuList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catelog.infrastructure.SkuList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.reactivesw.catelog.infrastructure.GrpcSku> sku_ =
      java.util.Collections.emptyList();
    private void ensureSkuIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        sku_ = new java.util.ArrayList<io.reactivesw.catelog.infrastructure.GrpcSku>(sku_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.infrastructure.GrpcSku, io.reactivesw.catelog.infrastructure.GrpcSku.Builder, io.reactivesw.catelog.infrastructure.GrpcSkuOrBuilder> skuBuilder_;

    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public java.util.List<io.reactivesw.catelog.infrastructure.GrpcSku> getSkuList() {
      if (skuBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sku_);
      } else {
        return skuBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public int getSkuCount() {
      if (skuBuilder_ == null) {
        return sku_.size();
      } else {
        return skuBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcSku getSku(int index) {
      if (skuBuilder_ == null) {
        return sku_.get(index);
      } else {
        return skuBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder setSku(
        int index, io.reactivesw.catelog.infrastructure.GrpcSku value) {
      if (skuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku_.set(index, value);
        onChanged();
      } else {
        skuBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder setSku(
        int index, io.reactivesw.catelog.infrastructure.GrpcSku.Builder builderForValue) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        sku_.set(index, builderForValue.build());
        onChanged();
      } else {
        skuBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder addSku(io.reactivesw.catelog.infrastructure.GrpcSku value) {
      if (skuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku_.add(value);
        onChanged();
      } else {
        skuBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder addSku(
        int index, io.reactivesw.catelog.infrastructure.GrpcSku value) {
      if (skuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku_.add(index, value);
        onChanged();
      } else {
        skuBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder addSku(
        io.reactivesw.catelog.infrastructure.GrpcSku.Builder builderForValue) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        sku_.add(builderForValue.build());
        onChanged();
      } else {
        skuBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder addSku(
        int index, io.reactivesw.catelog.infrastructure.GrpcSku.Builder builderForValue) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        sku_.add(index, builderForValue.build());
        onChanged();
      } else {
        skuBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder addAllSku(
        java.lang.Iterable<? extends io.reactivesw.catelog.infrastructure.GrpcSku> values) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sku_);
        onChanged();
      } else {
        skuBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder clearSku() {
      if (skuBuilder_ == null) {
        sku_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        skuBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public Builder removeSku(int index) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        sku_.remove(index);
        onChanged();
      } else {
        skuBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcSku.Builder getSkuBuilder(
        int index) {
      return getSkuFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcSkuOrBuilder getSkuOrBuilder(
        int index) {
      if (skuBuilder_ == null) {
        return sku_.get(index);  } else {
        return skuBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public java.util.List<? extends io.reactivesw.catelog.infrastructure.GrpcSkuOrBuilder> 
         getSkuOrBuilderList() {
      if (skuBuilder_ != null) {
        return skuBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sku_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcSku.Builder addSkuBuilder() {
      return getSkuFieldBuilder().addBuilder(
          io.reactivesw.catelog.infrastructure.GrpcSku.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public io.reactivesw.catelog.infrastructure.GrpcSku.Builder addSkuBuilder(
        int index) {
      return getSkuFieldBuilder().addBuilder(
          index, io.reactivesw.catelog.infrastructure.GrpcSku.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catelog.infrastructure.GrpcSku sku = 1;</code>
     */
    public java.util.List<io.reactivesw.catelog.infrastructure.GrpcSku.Builder> 
         getSkuBuilderList() {
      return getSkuFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.reactivesw.catelog.infrastructure.GrpcSku, io.reactivesw.catelog.infrastructure.GrpcSku.Builder, io.reactivesw.catelog.infrastructure.GrpcSkuOrBuilder> 
        getSkuFieldBuilder() {
      if (skuBuilder_ == null) {
        skuBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.reactivesw.catelog.infrastructure.GrpcSku, io.reactivesw.catelog.infrastructure.GrpcSku.Builder, io.reactivesw.catelog.infrastructure.GrpcSkuOrBuilder>(
                sku_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        sku_ = null;
      }
      return skuBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catelog.infrastructure.SkuList)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catelog.infrastructure.SkuList)
  private static final io.reactivesw.catelog.infrastructure.SkuList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catelog.infrastructure.SkuList();
  }

  public static io.reactivesw.catelog.infrastructure.SkuList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SkuList>
      PARSER = new com.google.protobuf.AbstractParser<SkuList>() {
    public SkuList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkuList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SkuList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SkuList> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catelog.infrastructure.SkuList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

