// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reactivesw-catelog.proto

package io.reactivesw.catelog.infrastructure;

public interface VariantInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catelog.grpc.VariantInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 displayOrder = 3;</code>
   */
  int getDisplayOrder();

  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 4;</code>
   */
  java.util.List<io.reactivesw.catelog.infrastructure.VariantValueInfo> 
      getVariantValueList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 4;</code>
   */
  io.reactivesw.catelog.infrastructure.VariantValueInfo getVariantValue(int index);
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 4;</code>
   */
  int getVariantValueCount();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 4;</code>
   */
  java.util.List<? extends io.reactivesw.catelog.infrastructure.VariantValueInfoOrBuilder> 
      getVariantValueOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catelog.grpc.VariantValueInfo variantValue = 4;</code>
   */
  io.reactivesw.catelog.infrastructure.VariantValueInfoOrBuilder getVariantValueOrBuilder(
      int index);
}
